[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
"aqua:go-task/task" = "latest"
buf = "latest"
go = "1"
node = "24"
ruby = "4.0"
uv = "latest"
xcbeautify = "latest"
xcodes = "latest"
