[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false

[tools]
"aqua:go-task/task" = "latest"
buf = "latest"
"gem:cocoapods" = "latest"
gh = "latest"
go = "1"
helm = "latest"
node = "24"
pnpm = "latest"
ruby = "4.0"
swiftgen = { version = "latest", exe = "swiftgen/bin/swiftgen" }
uv = "latest"
xcbeautify = "latest"
xcodes = "latest"
